sudo: required
services:
  - docker

before_install:
  - docker build -t weenta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true weenta/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-234044377448"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY





  